### ISSUE TITLE
Issue with exports

### ISSUE THREAD

**Issue by Harasz** [digitalbazaar/bitstring#12]
Hey team,
I was trying to use yours `vc-status-list` package, but when I tried to create a list I got fallowing error `TypeError: Bitstring is not a constructor`. I create a separate project to check what is exported from `@digitalbazaar/bitstring` package, I got empty object when it should be a `Bitstring` class.

Here is my script:
```
import Bitstring from '@digitalbazaar/bitstring';

console.log(Bitstring);
```
Expected: `[class Bitstring]`
Received: `{}`

I've installed the latest version of package. Tested on Node 16.10.0

**Comment by dlongley** [comment]
#11 should address this. The current version today is relying on `esm.js` to transpile -- which has some bugs in it that cause this problem. If you  are using node.js, you can import the current version of the package as CJS doing something like this:

```js
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const Bitstring = require('@digitalbazaar/bitstring');
```

We're working on updating a number of our packages *right now* to remove `esm.js` -- so a new version that works properly as an ESM import should be out in the very near future.

**Comment by davidlehn** [comment]
`vc-status-list` and this package are released and in module mode now.  There is no default export so you do need to import `Bitstring` directly now:
```js
import {Bitstring} from '@digitalbazaar/bitstring';
```
Closing this.  Reopen or create a new issue if there are more import issues.

**Comment by Harasz** [comment]
#11 completely drop support for `cjs` apps/libs. Second thing, have you think of using typescript here? Should be easy and fast, and we can add support for both `esm` and `cjs` apps. I can create a draft PR for that if you want
